config/routes.rb
Rails.application.routes.draw do


  get 'levels/index'
  post 'levels/create'
  get 'levels/delete'
  get 'levels/update'



  resources :questions
  get 'users/index'
  post 'users/create'

  get 'sessions/index'

  root 'questions#index'

  get 'questions/index'
  post 'questions/create'
  get 'questions/update'

  get 'questions/show'
  get 'users/show'
  get 'users/update'

  post 'sessions/create'

  get 'sessions/destroy'

  get 'labels/index'


  post 'labels/create'

  post 'questions_comments/create'
  post 'answers_comments/create'
  post 'answers/create'
  post 'cars/create'
  post 'cats/create'
  post 'dogs/create'
  post 'cows/create'

  get 'labels/delete'
  get 'labels/update'
  
  get 'faculties/index'
  get 'faculties/delete'
  post 'faculties/create'
  get 'faculties/update'
  get 'faculties/show'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  has_many :question_comments, dependent: :destroy
  has_many :question_votes, dependent: :destroy
  belongs_to :user
  belongs_to :faculty
  has_many :question_labels, dependent: :destroy
  validates :contenido, presence: true
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    $recargar=params
    @questions = filtered_questions
    @faculties = Faculty.all
    @answers = Answer.all
    @labels = Label.all
    @directions = Direction.all
    @users = User.all
    @questionvotes = QuestionVote.all

    flash[:auxIngReg] = nil #se pone en nula para que aparezca el cartel de ingresar/registrarse

  end

  def show
    #Mostrar una pregunta, la de id del parametro
    @question=Question.find(params[:id])
    #Si el usuario que entra no es el que creo la pregunta el contador de visitas se actualiza+1
    if session[:user_id]!=@question.user_id
      @question.num_visitas=@question.num_visitas+1
      @question.save
    end
    if params.has_key?(:answer_id) && @question.mejor_respuesta == nil
      @question.mejor_respuesta = params[:answer_id]
      @question.save
    end


    @answers = Answer.all
    @users = User.all
    @questionvotes = QuestionVote.all
    @questioncomments = QuestionComment.all
    @questioncommentvotes = QuestionCommentVote.all
    @answervotes = AnswerVote.all
    @answercomments = AnswerComment.all
    @answercommentvotes = AnswerCommentVote.all
    @questionlabel = QuestionLabel.all
    @labels = Label.all
    @faculties = Faculty.all
  end

  def mejor
    question_id = @question.id
    if params[:answer_id] != nil && @question.mejor_respuesta == nil
      @question.mejor_respuesta = params[:answer_id]
    end
    redirect_to "#{questions_path}/#{question_id}"
  end

  def new
     if session[:user_id]!=0
        @labels = Label.all
        @users = User.all
        @faculties =Faculty.all
        @directions=Direction.all
    else
       redirect_to root_path
    end
  end

  def create

    $recargar=params#Si llega a fallar, en $recargar, queda todos los parametros del formulario, para el rellenado
    etiquetas = params[:etiqueta]
    descripcion = params[:descripcion]

    if params[:question_id] == "0"
      if etiquetas != nil
        if etiquetas.size >= 1 && etiquetas.size <= 5
          if params[:pregunta]!=""
            pregunta=Question.new(num_visitas:0, contenido:params[:pregunta], descripcion:descripcion, user_id: session[:user_id], faculty_id: params[:facultad])
            #hay que guardar la pregunta
            if pregunta.save
               for i in (0..etiquetas.size-1)
                etiquetasPregunta=QuestionLabel.new(question_id:pregunta.id,label_id:etiquetas[i])
                if !etiquetasPregunta.save
                   break
                end
                end
                if i !=etiquetas.size-1
                  pregunta.destroy
                  flash[:message] = "Error no se creo la pregunta"
                else
               flash[:message] = "Pregunta Creada"
               $recargar=nil
             end
            else
               flash[:message] = "Error no se creo la pregunta"
            end
          else
            flash[:message] = "Debe ingresar una pregunta"
          end
        else
          flash[:message] = "Debe seleccionar entre 1 y 5 etiquetas"
        end
      else
        flash[:message] = "Debe seleccionar entre 1 y 5 etiquetas"
      end
      if flash[:message] != "Pregunta Creada"
        redirect_to new_question_path
      else
        redirect_to root_path
      end
    else
      update
    end

  end

  def filtered_questions
    result = Question.all
    user_id = session[:user_id]
    if user_id > 0
      fac_id = User.find(user_id).faculty_id  # obtengo el id de facultd del usuario
      if fac_id != 0
        result = result.where(faculty_id: fac_id) # si se tiene una facultad elegida filtro por esa facultad
      end
    end

    if params.has_key?(:facultad) # Si se clickeo el boton Buscar
      if params[:facultad] != "0" # Si la facultad elegida no es todas
                  if params.has_key?(:busqueda)# Si ingreso algo a buscar, dentro de una facultad
                    result = Question.all.where("contenido ILIKE ? OR descripcion ILIKE ?","%#{params[:busqueda]}%","%#{params[:busqueda]}%") # si se esta buscando algo se filtra en base a eso
                    result=result.where(faculty_id: params[:facultad])
                   else # Mostrar todas las preguntas de una facultad
                    result = Question.all.where(faculty_id: params[:facultad])
                  end
      else
                  if params.has_key?(:busqueda)# Si ingreso algo a buscar, en todas las facultades
                    result = Question.all.where("contenido ILIKE ? OR descripcion ILIKE ?","%#{params[:busqueda]}%","%#{params[:busqueda]}%") # si se esta buscando algo se filtra en base a eso
                   else # Muestro todas las preguntas
                    result = Question.all
                  end
      end

      if params[:etiqueta]!="0" # Si la etiqueta elegida no es todas
        #preguntasEtiqueta=QuestionLabel.joins("INNER JOIN labels ON labels.id = question_labels.label_id AND labels.id=1")
        #El JOIN queda identico que la linea de abajo
        preguntasEtiqueta=QuestionLabel.all.where(label_id: params[:etiqueta])
        arregloPreguntasid=preguntasEtiqueta.select(:question_id)
        result=result.where(id:arregloPreguntasid)
      else #Si es todas, dejo la busqueda como esta
        result=result
      end

    end

    if result.count == 0
      flash[:message] = "No se han encontrado resultados para su busqueda"
    end
    result.order(created_at: :desc) # se ordenan las preguntas a mostrar por fecha de creacion de mas reciente a mas antigua
  end

  def edit
    @user = User.find(session[:user_id])
    @question = Question.find(params[:id])
    @labels = Label.all
    @faculties = Faculty.all
    @directions = Direction.all
    @question_labels = QuestionLabel.all
  end

  def update
    $recargar=params#Si llega a fallar, en $recargar, queda todos los parametros del formulario, para el rellenado
    etiquetas = params[:etiqueta]
    descripcion = params[:descripcion]
    @user = User.find(session[:user_id])
    @question = Question.all.where(user_id: session[:user_id]).first

    if etiquetas != nil
      if etiquetas.size >= 1 && etiquetas.size <= 5
        if params[:pregunta]!=""
          pregunta=Question.new(num_visitas:0, contenido:params[:pregunta], descripcion:descripcion, user_id: session[:user_id], faculty_id: params[:facultad])
          #hay que guardar la pregunta
          if pregunta.save
             for i in (0..etiquetas.size-1)
              etiquetasPregunta=QuestionLabel.new(question_id:pregunta.id,label_id:etiquetas[i])
              if !etiquetasPregunta.save
                 break
              end
              end
              if i !=etiquetas.size-1
                pregunta.destroy
                flash[:message] = "Error no se modifico la pregunta"
              else
             flash[:message] = "Pregunta Modificada"
             $recargar=nil
           end
          else
             flash[:message] = "Error no se modifico la pregunta"
          end
        else
          flash[:message] = "Debe ingresar una pregunta"
        end
      else
        flash[:message] = "Debe seleccionar entre 1 y 5 etiquetas"
      end
    else
      flash[:message] = "Debe seleccionar entre 1 y 5 etiquetas"
    end

    if flash[:message] != "Pregunta Modificada"
      redirect_to "/questions/#{@question.id}/edit"
    else
      @question.contenido = pregunta.contenido
      @question.descripcion = pregunta.descripcion
      @question.faculty_id = pregunta.faculty_id
      QuestionLabel.where(question_id: @question.id).each do |l|
        l.destroy
      end
      QuestionLabel.where(question_id: pregunta.id).each do |l|
        l.question_id = @question.id
        l.save
      end
      @question.save
      pregunta.destroy
      redirect_to root_path
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_answerbuttons.html.erb
<div class="btn-group">
  <form  action="/cats/create" method="post" >
    <%if session[:user_id]!=0%>
      <%if @answervotes.where(answer_id:@resp.id,user_id:session[:user_id]).count ==0 && session[:user_id]!=@resp.user_id%>

          <input type="hidden" name="question_id" value=<%= @question.id%>>
          <input type="hidden" name="answer_id" value=<%= @resp.id%>>
          <input type="hidden" name="votoP_A" id="votoP_A<%=@resp.id%>" value="0">
          <input type="hidden" name="votoN_A" id="votoN_A<%=@resp.id%>" value="0">

          <% if Usuario.new(session[:user_id]).getFuncionalidad("Votar Positivo")%>
            <button type="submit" class="btn btn-success" onclick="votoPositivo_A(<%=@resp.id%>)">
              <span class='glyphicon glyphicon-thumbs-up'></span>
            </button>
          <%end%>

          <% if Usuario.new(session[:user_id]).getFuncionalidad("Votar Negativo")%>
            <button type="submit" class="btn btn-danger" onclick="votoNegativo_A(<%=@resp.id%>)">
              <span class='glyphicon glyphicon-thumbs-down'></span>
            </button>
          <%end%>

      <%else%>
        <% if (session[:user_id]!=@resp.user_id)%>
          <%if @answervotes.where(answer_id:@resp.id,user_id:session[:user_id]).first != nil %>
          <button  class="btn btn-info" disabled>
            <%if @answervotes.where(answer_id:@resp.id,user_id:session[:user_id]).first.tipo%>
              <span>Ya votaste positivo</span>
            <%else%>
              <span>Ya votaste negativo</span>
            <%end%>
          </button>
          <%end%>
        <%end%>
      <%end%>

      <% if Usuario.new(session[:user_id]).getFuncionalidad("Comentar")%>
        <a type="button" class="btn btn-success" onclick='verEscribirComentarioResp(<%=@resp.id%>)'> Escribir Comentario
          <span class='glyphicon glyphicon-comment'></span>
        </a>
      <%end%>


    <%end%>
    <button type="button" class="btn btn-success" onclick="verComentariosResp(<%=@resp.id%>)"> Ver/Ocultar Comentarios
      <span class='glyphicon glyphicon-plus'></span>
    </button>
  </form>

  <script>

    function votoPositivo_A(answers_id) {
    votoP_A_id = "votoP_A" + answers_id;
    document.getElementById(votoP_A_id).value = "1" }

    function votoNegativo_A(answers_id) {
    votoN_A_id = "votoN_A" + answers_id;
    document.getElementById(votoN_A_id).value = "1" }

    function verEscribirComentarioResp(id) {  // despliega el escribir comentario si esta oculto y oculta si esta desplegado
      comen = "comen" + id;
      if (document.getElementById(id).style.display == 'block') {
        document.getElementById(id).style.display = 'none' }
      else {
        document.getElementById(id).style.display = 'block' }
        document.getElementById(comen).style.display = 'none' }

    function verComentariosResp(id) {  // despliega los comentarios si estan ocultos y oculta si estan desplegados
      comen = "comen" + id;
      if (document.getElementById(comen).style.display == 'block') {
        document.getElementById(comen).style.display = 'none' }
      else {
        document.getElementById(comen).style.display = 'block' }
        document.getElementById(id).style.display = 'none' }
  </script>
</div>
<form  action="#{questions_path}/#{question_id}" method="get" > <!-- Falta definir a que controller llamar -->
  <%if @question.user_id == session[:user_id]  %>
    <% if @question.mejor_respuesta == nil %>
      <input type="hidden" name="id" value=<%= @question.id%>>
      <input type="hidden" name="answer_id" value=<%= @resp.id%>>
      <button type="submit" class="btn btn-warning" style="margin-top:5px ; margin-left:88%">¿Mejor Respuesta?
        <span class='glyphicon glyphicon-star'></span>
      </button>
    <%end%>
  <%end%>
</form>

app/views/questions/_answercommentbuttons.html.erb
<div class="btn-group">
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css">
  <form  action="/cows/create" method="post" >
     <input type="hidden" name="answer_comment_id" value=<%= @comentarioR.id%>>
     <input type="hidden" name="votoP_CA" id="votoP_CA<%=@comentarioR.id%>" value="0">
     <input type="hidden" name="votoN_CA" id="votoN_CA<%=@comentarioR.id%>" value="0">
     <input type="hidden" name="question_id" value=<%=@question.id%>>
     <div class="btn-group">
        <%if session[:user_id]!=0%>
          <%if (@answercommentvotes.where(answer_comment_id:@comentarioR.id,user_id:session[:user_id]).count ==0) && (session[:user_id]!=@comentarioR.user_id)%>

            <% if Usuario.new(session[:user_id]).getFuncionalidad("Votar Positivo")%>
              <button type="submit" class="btn btn-success" onclick='votoPositivoCA(<%=@comentarioR.id%>)'>
                <span class='glyphicon glyphicon-thumbs-up'></span>
              </button>
            <%end%>

            <% if Usuario.new(session[:user_id]).getFuncionalidad("Votar Negativo")%>
              <button type="submit" class="btn btn-danger" onclick='votoNegtivoCA(<%=@comentarioR.id%>)'>
               <span class='glyphicon glyphicon-thumbs-down'></span>
              </button>
            <%end%>

          <%else%>
            <% if (session[:user_id]!=@comentarioR.user_id)%>
              <%if @answercommentvotes.where(answer_comment_id:@comentarioR.id,user_id:session[:user_id]).first != nil%>
              <button  class="btn btn-info" disabled>
                <%if @answercommentvotes.where(answer_comment_id:@comentarioR.id,user_id:session[:user_id]).first.tipo%>
                  <span>Ya votaste positivo</span>
                <%else%>
                  <span>Ya votaste negativo</span>
                <%end%>
              </button>
              <%end%>
            <%end%>
          <%end%>
        <%end%>
    </div>
  </form>
</div>

<script>

  function votoPositivoCA(comment_id)
  {

    votoP_id = "votoP_CA" + comment_id;
    document.getElementById(votoP_id).value = "1"
  }

  function votoNegtivoCA(comment_id)
  {

    votoN_id = "votoN_CA" + comment_id;

  document.getElementById(votoN_id).value = "1"
  }

</script>

app/views/questions/_answercommentinfo.html.erb
<%valoracionP=0%>
<%valoracionN=0%>
 <%if @answercommentvotes.where(answer_comment_id:@comentarioR.id).count !=0%>
   <% @answercommentvotes.where(answer_comment_id:@comentarioR.id).each do|voto|%>
    <%if voto.tipo%>
      <%valoracionP =valoracionP+1%>
    <%else%>
      <%valoracionN =valoracionN+1%>
    <%end%>
   <%end%>
 <%end%>
<h5 class="mb-1 text-center"><%= @comentarioR.contenido %></h5>
<%= link_to users_show_path(@comentarioR.user_id) do %>
  <kbd> <%= @users.find(@comentarioR.user_id).nombre%> <%= @users.find(@comentarioR.user_id).apellido%><br></kbd>
<%end%>

<small> <%= @comentarioR.created_at.strftime("%d/%m/%Y %H:%M:%S")%><br></small>
<small>Votos positivos: <%=valoracionP%><br>Votos negativos: <%=valoracionN%><br></small>

app/views/questions/_answerinfo.html.erb
<%valoracionP=0%>
<%valoracionN=0%>
<%if @answervotes.where(answer_id:@resp.id).count !=0%>
  <% @answervotes.where(answer_id:@resp.id).each do|voto|%>
    <%if voto.tipo%>
      <%valoracionP =valoracionP+1%>
    <%else%>
      <%valoracionN =valoracionN+1%>
    <%end%>
  <%end%>
<%end%>



<h5 class="mb-1 text-center"><%= @resp.contenido %><br></h5>
<div>
  <% if @resp.id == @question.mejor_respuesta %>
       <span class='glyphicon glyphicon-star' style="color:yellow; font-size: 20px"></span> Mejor respuesta
  <%end%>
</div>
<%= link_to users_show_path(@resp.user_id) do %>
  <kbd><%= "#{@users.find(@resp.user_id).nombre} #{@users.find(@resp.user_id).apellido}"%><br></kbd>
<%end%>
<small> <%= @resp.created_at.strftime("%d/%m/%Y %H:%M:%S")%><br></small>
<small>Votos positivos: <%=valoracionP%><br>Votos negativos: <%=valoracionN%><br></small>

app/views/questions/_filtro.html.erb
<div class="row" data-pg-collapsed style="margin-top: 50px;padding:10px;background">
    <nav class="navbar navbar-default" role="navigation" data-pg-collapsed>
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Educanding</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <form class="navbar-form navbar-left" role="search" action="/questions" method="get">
                  <div class="form-group" style="margin-right: 25px;" data-pg-collapsed>
                    <label class="control-label" for="facultad" style="margin-right: 5px;" >Facultad</label>
                    <select id="facultad"  name="facultad" class="form-control" style="width:125px;">
                        <option value =0 selected>Todas</option>
                        <% @faculties.order(:nombre).each do |facultad| %>
                            <%if session[:user_id]!=0%><!--El usuario esta registrado -->
                              <%if $recargar[:facultad]!=nil%><!-- Se mando a buscar -->
                                  <%if $recargar[:facultad]!="0"%><!-- La busqueda no es Todas -->
                                      <%if $recargar[:facultad]=="#{facultad.id}"%><!-- La facultad coincide con la facultad buscada -->
                                        <option value=<%=facultad.id%> selected><%=facultad.nombre%> - <%=@directions.find(facultad.direction_id).ciudad%>, <%=@directions.find(facultad.direction_id).calle%></option>
                                      <%else%>
                                        <option value=<%=facultad.id%>><%=facultad.nombre%> - <%=@directions.find(facultad.direction_id).ciudad%>, <%=@directions.find(facultad.direction_id).calle%></option>
                                      <%end%>
                                  <%else%><!-- La busqueda es Todas -->
                                    <option value=<%=facultad.id%>><%=facultad.nombre%> - <%=@directions.find(facultad.direction_id).ciudad%>, <%=@directions.find(facultad.direction_id).calle%></option>
                                  <%end%>
                              <%else%><!-- No se mando a buscar -->
                                  <%if @users.find(session[:user_id]).faculty_id==facultad.id%>
                                    <option value=<%=facultad.id%> selected><%=facultad.nombre%> - <%=@directions.find(facultad.direction_id).ciudad%>, <%=@directions.find(facultad.direction_id).calle%></option>
                                  <%else%>
                                    <option value=<%=facultad.id%>><%=facultad.nombre%> - <%=@directions.find(facultad.direction_id).ciudad%>, <%=@directions.find(facultad.direction_id).calle%></option>
                                  <%end%>
                              <%end%>
                            <%else%><!-- El usuario no esta registrado -->
                            <%if $recargar[:facultad]!=nil%><!-- Se mando a buscar -->
                                  <%if $recargar[:facultad]!="0"%><!-- La busqueda no es Todas -->
                                      <%if $recargar[:facultad]=="#{facultad.id}"%><!-- La facultad coincide con la facultad buscada -->
                                        <option value=<%=facultad.id%> selected><%=facultad.nombre%> - <%=@directions.find(facultad.direction_id).ciudad%>, <%=@directions.find(facultad.direction_id).calle%></option>
                                      <%else%>
                                        <option value=<%=facultad.id%>><%=facultad.nombre%> - <%=@directions.find(facultad.direction_id).ciudad%>, <%=@directions.find(facultad.direction_id).calle%></option>
                                      <%end%>
                                  <%else%><!-- La busqueda es Todas -->
                                    <option value=<%=facultad.id%>><%=facultad.nombre%> - <%=@directions.find(facultad.direction_id).ciudad%>, <%=@directions.find(facultad.direction_id).calle%></option>
                                  <%end%>
                              <%else%><!-- No se mando a buscar -->
                               <option value=<%=facultad.id%>><%=facultad.nombre%> - <%=@directions.find(facultad.direction_id).ciudad%>, <%=@directions.find(facultad.direction_id).calle%></option>
                              <%end%>
                            <%end%>
                        <% end %>
                    </select>
                  </div>
                  <div class="form-group" style="margin-right: 25px;" data-pg-collapsed>
                    <label class="control-label" for="etiqueta" style="margin-right: 5px;">Etiquetas</label>
                    <select id="etiqueta"  name="etiqueta" class="form-control" style="width:125px;">
                        <option value=0 selected>Todas</option>
                        <% @labels.order(:nombre).each do |etiqueta| %>
                          <%if $recargar[:etiqueta]!=nil%><!-- Se mando a buscar -->
                            <%if $recargar[:etiqueta]!="0"%><!-- La busqueda no es Todas -->
                              <%if $recargar[:etiqueta]=="#{etiqueta.id}"%><!-- La etiqueta coincide con la etiqueta buscada -->
                                <option value=<%=etiqueta.id%> selected><%=etiqueta.nombre%></option>
                              <%else%>
                                <option value=<%=etiqueta.id%>> <%=etiqueta.nombre%></option>
                              <%end%>
                            <%else%><!-- La busqueda es Todas -->
                              <option value=<%=etiqueta.id%>> <%=etiqueta.nombre%></option>
                            <%end%>
                          <%else%><!-- No se mando a buscar -->
                            <option value=<%=etiqueta.id%>> <%=etiqueta.nombre%></option>
                          <%end%>
                        <% end %>
                    </select>
                  </div>
                  <script type="text/javascript"><!-- Script que al terminar de cargar la pagina, carga los valores de la anterior -->
                    window.onload = function()
                    {
                        document.getElementById("busqueda").value = "<%=$recargar[:busqueda]%>";
                    }
                   </script>
                   <%$recargar=nil%>
                  <div class="form-group">
                      <input id="busqueda" type="text" name="busqueda" class="form-control" placeholder="Buscar" >
                  </div>
                  <button type="submit" class="btn btn-default">Buscar</button>
                </form>

                <% if Usuario.new(session[:user_id]).getFuncionalidad("Preguntar")%>

                  <ul class="nav navbar-nav" style="margin-left:50px">
                      <li >
                          <a href= <%= "#{new_question_path}" %> >Crear Pregunta</a>
                      </li>
                  </ul>

                <%end%>

                <ul class="nav navbar-nav " style="margin-right:25px">
                    <li>
                         <a href= <%= "#{root_path}" %>>Mostrar Todas</a>
                    </li>
                </ul>
                <ul class="nav navbar-nav " style="margin-right:25px">
                    <li>
                         <a href= <%= "#{faculties_show_path}" %>>Ranking Facultades</a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right" style="margin-right:50px">
                    <li>
                        <a href="#">Manual de Uso</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</div>

app/views/questions/_question.html.erb
<a href=<%="#{questions_path}/#{@question.id}"%> class="list-group-item list-group-item-action flex-column align-items-start active" style="background-color: #5a96ba;margin-bottom:10px">
  <div style="padding-left: 10%;padding-right: 10%;">
        <%valoracion=0%>
        <%if @questionvotes.where(question_id:@question.id).count !=0%>
        	<% @questionvotes.where(question_id:@question.id).each do|voto|%>
        		<%if voto.tipo%>
        			<%valoracion =valoracion+1%>
       			 <%else%>
       				<%valoracion =valoracion-1%>
       		 	<%end%>
       		 <%end%>
       	<%end%>
        <h5 class="mb-1 text-center"><%= @question.contenido %> </h5>
        <medium><%= "#{@users.find(@question.user_id).nombre} #{@users.find(@question.user_id).apellido}"%><br></medium>
        <small> <%= @question.created_at.strftime("%d/%m/%Y %H:%M:%S")%><br></small>
        <small>Valoracion: <%= valoracion%><br></small>
        <small>Numero de visitas: <%= @question.num_visitas%><br></small>
        <small>Numero de respuestas: <%= @answers.where(question_id:@question.id).count%></small>
        <%if @question.faculty_id != 0%>
          <small><br>Facultad: <%= @faculties.find(@question.faculty_id).nombre%><br></small>
        <%end%>
  </div>
</a>

app/views/questions/_questioncommentinfo.html.erb
<%valoracionP=0%>
<%valoracionN=0%>
 <%if @questioncommentvotes.where(question_comment_id:@comentario.id).count !=0%>
   <% @questioncommentvotes.where(question_comment_id:@comentario.id).each do|voto|%>
    <%if voto.tipo%>
      <%valoracionP =valoracionP+1%>
    <%else%>
      <%valoracionN =valoracionN+1%>
    <%end%>
   <%end%>
 <%end%>
<h5 class="mb-1 text-center"><%= @comentario.contenido %></h5>
<%= link_to users_show_path(@comentario.user_id) do %>
  <kbd> <%= @users.find(@comentario.user_id).nombre%> <%= @users.find(@comentario.user_id).apellido%><br></kbd>
<%end%>
<small> <%= @comentario.created_at.strftime("%d/%m/%Y %H:%M:%S")%><br></small>
<small>Votos positivos: <%=valoracionP%><br>Votos negativos: <%=valoracionN%><br></small>

app/views/questions/_questioninfo.html.erb
<%valoracionP=0%>
<%valoracionN=0%>
<%if @questionvotes.where(question_id:@question.id).count !=0%>
  <% @questionvotes.where(question_id:@question.id).each do|voto|%>
    <%if voto.tipo%>
      <%valoracionP =valoracionP+1%>
    <%else%>
      <%valoracionN =valoracionN+1%>
    <%end%>
  <%end%>
<%end%>
<h4 class="mb-1 text-center"><%= @question.contenido %> </h4>
<% if @question.descripcion != ""%>
  <h5 class="mb-1 text-center"><%= @question.descripcion %> </h5>
<% end %>
<%= link_to users_show_path(@question.user_id) do %>
  <kbd>
    <%= "#{@users.find(@question.user_id).nombre} #{@users.find(@question.user_id).apellido}"%>
  </kbd>
<%end%>
<small><br><%= @question.created_at.strftime("%d/%m/%Y %H:%M:%S")%><br></small>
<small>Votos positivos: <%=valoracionP%><br>Votos negativos: <%=valoracionN%><br></small>
<small>Numero de visitas: <%= @question.num_visitas%><br></small>
<small>Etiquetas:
  <div class="btn-group btn-group-xs">
    <% @questionlabel.where(question_id:@question.id).each do |l| %>
      <button type="button" class="btn btn-info"><%=@labels.find(l.label_id).nombre %></button>
    <%end%>
  </div>
  <br><br>
</small>