config/routes.rb
Rails.application.routes.draw do


  get 'levels/index'
  post 'levels/create'
  get 'levels/delete'
  get 'levels/update'



  resources :questions
  get 'users/index'
  post 'users/create'

  get 'sessions/index'

  root 'questions#index'

  get 'questions/index'
  post 'questions/create'
  get 'questions/update'

  get 'questions/show'
  get 'users/show'
  get 'users/update'

  post 'sessions/create'

  get 'sessions/destroy'

  get 'labels/index'


  post 'labels/create'

  post 'questions_comments/create'
  post 'answers_comments/create'
  post 'answers/create'
  post 'cars/create'
  post 'cats/create'
  post 'dogs/create'
  post 'cows/create'

  get 'labels/delete'
  get 'labels/update'
  
  get 'faculties/index'
  get 'faculties/delete'
  post 'faculties/create'
  get 'faculties/update'
  get 'faculties/show'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/faculty.rb
class Faculty < ApplicationRecord
  belongs_to :direction
  has_many :question
  has_many :users
  validates :nombre, presence: true, uniqueness: true
end

app/controllers/faculties_controller.rb
class FacultiesController < ApplicationController
  def index
    if Usuario.new(session[:user_id]).getFuncionalidad("Administrar Facultades")
      @faculties=Faculty.all
      @directions=Direction.all
    else
      flash[:message]="No tiene acceso a la ruta de recien"
      redirect_to root_path
    end
  end

  def create

    if params[:nombre]!="" && params[:ciudad]!="" && params[:direccion]!="" #si no esta vacio

      nombre=params[:nombre].capitalize
      ciudad=params[:ciudad].capitalize
      calle=params[:direccion].capitalize

      if Faculty.where(nombre:nombre).count==0#Si no existe la facultad

        if Direction.where(ciudad:ciudad,calle:calle).count==0#Si no existe la facultad

          direccion = Direction.new(ciudad:ciudad,calle:calle)
          if direccion.save
            facultad=Faculty.new(nombre: nombre,direction_id:direccion.id,activo:true)
            if facultad.save#si se puede guardar

              flash[:messageOk] = true
              flash[:message] = "Facultad creada"
            else#Si no se guardo, sale el error
              #este es un mensaje que se guarda en la variable global flash
              flash[:message] = "No se pudo crear la facultad"
              flash[:messageError] = true

            end
          else#Si no se guardo, sale el error
            #este es un mensaje que se guarda en la variable global flash
            flash[:message] = "No se pudo crear la facultdad"
            flash[:messageError] = true

          end

        else #Si la direccion existe
          flash[:message] = "La direccion ingresada ya existe"
          flash[:messageError] = true

        end

      else#Si la facultad existe

        if Faculty.where(nombre:nombre).first.activo==true
          #este es un mensaje que se guarda en la variable global flash
          flash[:message] = "La facultad ya existe"
          flash[:messageError] = false
        else

          if Direction.where(ciudad:ciudad,calle:calle).count==0#Si no existe la facultad

            facultad=Faculty.where(nombre:nombre).first
            facultad.activo = true
            if facultad.save#Si no se guardo, sale el error
              direccion = Direction.where(id:facultad.direction_id).first
              direccion.ciudad = ciudad
              direccion.calle = calle
              direccion.activo = true
              if direccion.save
                flash[:message] = "Facultdad creada"
                flash[:messageOk] = true
                redirect_to faculties_index_path
              else
                flash[:message] = "No se pudo crear la facultad"
                flash[:messageError] = true
              end
            else
              flash[:message] = "No se pudo crear la facultad"
              flash[:messageError] = true
            end

          else #Si  la facultad  existe

            direccion = Direction.where(ciudad:ciudad,calle:calle).first
            facultad=Faculty.where(nombre:nombre,ciudad:ciudad).first

            if direccion.id == facultad.direction_id
              facultad.activo = true
              direccion.activo = true
              if facultad.save && direccion.save #Si no se guardo, sale el error
                flash[:message] = "Facultad creada"
                flash[:messageOk] = true
              else
                flash[:message] = "No se pudo crear la facultad"
                flash[:messageError] = true
              end
            else
              flash[:message] = "la direccion ya existe"
              flash[:messageError] = true
            end

            flash[:message] = "la direccion ya existe"
            flash[:messageError] = true

          end

        end
      end

    else
      flash[:message] = "Debe completar los campos"
      flash[:messageError] = true
    end

    redirect_to faculties_index_path


  end



  def show
    @faculties=Faculty.all
    @directions=Direction.all
    order=[]# Arreglo que contiene cada elemento, en la primer posicion la cantidad de preguntas que tiene una facutad, y como segundo el id de la facultad
    i=0
    Faculty.all.each do |facultad|
      order[i]=[Question.where(faculty_id:facultad.id).count,facultad.id]
      i=i+1
    end
    @mayores=order.sort.reverse
  end

  def destroy
  end

  def update

    if params[:nombre]!="" && params[:ciudad]!="" && params[:direccion]!="" #si no esta vacio

      nombre=params[:nombre].capitalize
      ciudad=params[:ciudad].capitalize
      calle=params[:direccion].capitalize

      if Faculty.where(nombre:nombre).count==0#Si no existe la facultad

        if Direction.where(ciudad:ciudad,calle:calle).count==0#Si no existe la facultad

          facultad = Faculty.where(id:params[:faculty_id]).first
          facultad.nombre = nombre
          direccion = Direction.where(id:facultad.id).first
          direccion.calle=calle
          direccion.ciudad=ciudad
          if facultad.save && direccion.save
            flash[:message] = "Facultad modificada"
            flash[:messageOk] = true
          else
            flash[:message] = "No se pudo modificar la facultad"
            flash[:messageError] = true
          end

        else

          facultad = Faculty.where(id:params[:faculty_id]).first
          direccion = Direction.where(id:facultad.id).first

          if Direction.where(ciudad:ciudad,calle:calle).first.id == direccion.id
            facultad.nombre = nombre
            if facultad.save
              flash[:message] = "Facultad modificada"
              flash[:messageOk] = true
            else
              flash[:message] = "No se pudo modificar la facultad"
              flash[:messageError] = true
            end
          else
            flash[:message] = "La direccion ingresada corresponde a otro facultad"
            flash[:messageError] = true
          end


        end

      else

        facultad = Faculty.where(id:params[:faculty_id]).first
        if Faculty.where(nombre:nombre).first.id == facultad.id
          direccion = Direction.where(id:facultad.id).first

          if Direction.where(ciudad:ciudad,calle:calle).count==0
            direccion.ciudad=ciudad
            direccion.calle = calle
            if direccion.save
              flash[:message] = "Facultad modificada"
              flash[:messageOk] = true
            else
              flash[:message] = "No se pudo modificar la facultad"
              flash[:messageError] = true
            end
          else
            if Direction.where(ciudad:ciudad,calle:calle).first.id == direccion.id
              flash[:message] = "No hay modificaciones para hacer"
              flash[:messageOk] = true
            else
              flash[:message] = "La direccion ingresada pertenece a otra facultdad"
              flash[:messageError] = true
            end
          end
        else
          flash[:message] = "El nombre ingresado pertenece a otra facultdad"
          flash[:messageError] = true
        end
      end

    else
      flash[:message] = "Debe completar los campos"
      flash[:messageError] = true
    end

    redirect_to faculties_index_path


  end



   def delete
    if session[:user_id]!=0 && Usuario.new(session[:user_id]).getFuncionalidad("Administrar Facultades")
      @facu=Faculty.find(params[:format])
      @facu.activo = false
      @facu.save
      dire=Direction.find(@facu.direction_id)
      if Faculty.where(direction_id:dire.id).where(activo: true).count == 0#Si la direccion, no esta en ninguna faculta activa
        dire.activo = false#borrado logico de direccion
        dire.save
      end
      checkeoSinRelaciones
      redirect_to faculties_index_path
    end
  end

  def checkeoSinRelaciones
    if Question.all.where(faculty_id:@facu.id).count==0 && User.all.where(faculty_id:@facu.id).count==0
        @facu.destroy
        dire=Direction.find(@facu.direction_id)
        if Faculty.where(direction_id:dire.id).count == 0
          dire.destroy
        end
    end
  end

end

app/views/faculties/index.html.erb
<%flash[:auxVerPerfil] = nil%>

<script type="text/javascript">
function Mostrar(faculty_id)
{
    formUpdate= "formUpdate" + faculty_id;
    if(document.getElementById(formUpdate).style.display!="block")
      document.getElementById(formUpdate).style.display="block"
    else
      document.getElementById(formUpdate).style.display="none"
}
</script>

<% if flash[:messageError] != nil %>
  <% @color="red" %>
  <%= render '/mensaje/mensaje'  %>
<% end %>
<% if flash[:messageOk] != nil %>
  <% @color="green" %>
  <%= render '/mensaje/mensaje'  %>
<% end %>


<ul class="list-group">


  <%@faculties.order(:nombre).each do |facultad|%>
  <%if facultad.activo == true %>
    <li class="list-group-item">
    <%= facultad.nombre %>
    <button type="button" class="btn btn-warning" onclick="Mostrar(<%=facultad.id%>)">Modificar</button>
    <%= link_to faculties_delete_path(facultad.id) do %>
      <button type="button" class="btn btn-danger">Eliminar</button>
    <%end%>
    <form form class="" action="/faculties/update" id="formUpdate<%=facultad.id%>" method="get" style="display:none;margin-top:10px">

      <input type="hidden"  name="faculty_id" id="faculty_id" value="<%=facultad.id%>">


      <div class="form-group">

        <div style="padding:10px">
          <label for="nombre">Nuevo Nombre:</label>
          <input type="text"  name="nombre" id="nombre" required style="text-transform: capitalize">
       </div>
       <div style="padding:10px;float:bottom">
          <label for="ciudad">Nueva Ciudad:</label>
          <input type="text"  name="ciudad" id="ciudad" required style="text-transform: capitalize">
       </div>
       <div style="padding:10px;float:bottom">
          <label for="direccion">Nueva Direccion:</label>
          <input type="text"  name="direccion" id="direccion" required style="text-transform: capitalize">
       </div>
       <div style="padding:10px;float:bottom">
         <button class="btn  btn-primary" type="submit" >Modificar Facultad</button>
       </div>


      </div>
    </form>
    <br>
    <%=@directions.find(facultad.direction_id).ciudad%>, <%=@directions.find(facultad.direction_id).calle%>
    </li>
  <%end%>
  <%end%>
<% if session[:user_id] != 0 %>
  <li class="list-group-item " style="padding:30px">

      <h3 style="color:rgb(5,50,150)">Nueva Facultad</h3>  <br>


        <form class="form-inline" action="/faculties/create" method="post" style="width:50%">
          <div class="form-group">
          <div style="padding:10px">
           <label for="nombre">Nombre:</label>
           <input type="text" class="form-control" name="nombre" id="nombre" style="text-transform: capitalize" pattern="[A-Za-z0-9]+" title="Solo letras y Numeros">
         </div>
         <div style="padding:10px;float:bottom">
           <label for="ciudad">Ciudad:</label>
           <input type="text" class="form-control" name="ciudad" id="ciudad" style="text-transform: capitalize" pattern="[A-Za-z0-9]+" title="Solo letras y Numeros">


         </div>
         <div style="padding:10px;float:bottom">
           <label for="direccion">Direccion:</label>
           <input type="text" class="form-control" name="direccion" id="direccion" style="text-transform: capitalize" pattern="[A-Za-z0-9]+" title="Solo letras y Numeros">
         </div>

         <div style="padding:10px;float:bottom">
           <input class="btn btn-lg btn-primary" type="submit" style="" value="Crear Facultad">
         </div>

          </div>




    </form>
  </li>
  <%end%>

</ul>

app/views/faculties/show.html.erb
<div class="container">
	<h3 class="text-center">Facultades con mayor cantidad de preguntas</h3>
	<br>

	<table class="table table-bordered">
    <thead>
      <tr bgcolor="white">
        <th class="text-center">Posicion</th>
        <th class="text-center">Facultad</th>
        <th class="text-center">Ciudad</th>
				<th class="text-center">Direccion</th>
				<th class="text-center">Preguntas</th>
      </tr>
    </thead>
    <tbody>
			<% i = 0 %>
			<%@mayores.each do |facultad|%>
					<% i = i+1 %>
					<tr bgcolor="white">
						<td class="text-center"><%=i%></td>
						<td class="text-center"><%= @faculties.find(facultad[1]).nombre %></td>
						<td class="text-center"><%=@directions.find(@faculties.find(facultad[1]).direction_id).ciudad%></td>
						<td class="text-center"><%=@directions.find(@faculties.find(facultad[1]).direction_id).calle%></td>
						<td class="text-center"><%=facultad[0]%></td>
					</tr>
			<%end%>
    </tbody>
  </table>
	<!--
	<ul class="list-group">

		<%@mayores.each do |facultad|%>

	    	<li class="list-group-item">
			  <%= @faculties.find(facultad[1]).nombre %>
			  <br>
			  <%=@directions.find(@faculties.find(facultad[1]).direction_id).ciudad%>, <%=@directions.find(@faculties.find(facultad[1]).direction_id).calle%>
			  <br>
			  Cantidad de Preguntas: <%=facultad[0]%>
	 		</li>
		<%end%>
	</ul>
	-->
</div>