config/routes.rb
Rails.application.routes.draw do


  get 'levels/index'
  post 'levels/create'
  get 'levels/delete'
  get 'levels/update'



  resources :questions
  get 'users/index'
  post 'users/create'

  get 'sessions/index'

  root 'questions#index'

  get 'questions/index'
  post 'questions/create'
  get 'questions/update'

  get 'questions/show'
  get 'users/show'
  get 'users/update'

  post 'sessions/create'

  get 'sessions/destroy'

  get 'labels/index'


  post 'labels/create'

  post 'questions_comments/create'
  post 'answers_comments/create'
  post 'answers/create'
  post 'cars/create'
  post 'cats/create'
  post 'dogs/create'
  post 'cows/create'

  get 'labels/delete'
  get 'labels/update'
  
  get 'faculties/index'
  get 'faculties/delete'
  post 'faculties/create'
  get 'faculties/update'
  get 'faculties/show'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  has_many :answer_comments, dependent: :destroy
  has_many :answer_votes, dependent: :destroy
  belongs_to :question
  belongs_to :user
  validates :contenido, presence: true
end

app/models/answer_comment.rb
class AnswerComment < ApplicationRecord
  has_many :answer_comment_votes, dependent: :destroy
  belongs_to :answer
  belongs_to :user
  validates :contenido, presence: true
end

app/models/answer_vote.rb
class AnswerVote < ApplicationRecord
  belongs_to :answer
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/direction.rb
class Direction < ApplicationRecord
  has_many :faculties
  validates :ciudad, presence: true
  validates :calle, presence: true
end

app/models/faculty.rb
class Faculty < ApplicationRecord
  belongs_to :direction
  has_many :question
  has_many :users
  validates :nombre, presence: true, uniqueness: true
end

app/models/functionality.rb
class Functionality < ApplicationRecord

  has_many :level_functionalities, dependent: :destroy

end

app/models/label.rb
class Label < ApplicationRecord
  has_many :question_labels, dependent: :destroy
  validates :nombre, presence: true, uniqueness: true
end

app/models/level.rb
class Level < ApplicationRecord
  has_many :users
  validates :nombre, presence: true
  validates :puntos, presence: true

  has_many :level_functionalities, dependent: :destroy



end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  has_many :question_comments, dependent: :destroy
  has_many :question_votes, dependent: :destroy
  belongs_to :user
  belongs_to :faculty
  has_many :question_labels, dependent: :destroy
  validates :contenido, presence: true
end

app/models/question_comment.rb
class QuestionComment < ApplicationRecord
  has_many :question_comment_votes, dependent: :destroy
  belongs_to :question
  belongs_to :user
  validates :contenido, presence: true
end

app/models/question_label.rb
class QuestionLabel < ApplicationRecord
  belongs_to :question
  belongs_to :label
end

app/models/question_vote.rb
class QuestionVote < ApplicationRecord
  belongs_to :question
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :level
  belongs_to :faculty, optional:true
  has_many :questions
  has_many :answer
  has_many :question_comments
  has_many :answer_comments
  has_many :question_votes
  has_many :answer_votes
  has_many :question_comment_votes
  has_many :answer_comment_votes
  validates :nombre, presence: true
  validates :apellido, presence: true
  validates :mail, presence: true, uniqueness: true
  validates :pass, presence: true
end

app/models/usuario.rb
class Usuario

  # método inicializar clase
  def initialize(id)

    if id > 0
      @user = User.find(id)
    else
      @user = nil
    end

  end

  def getFuncionalidad(funcionalidad)

    if @user != nil

      functionality_id = Functionality.all.where(nombre:funcionalidad).first.id

      if ( LevelFunctionality.all.where(level_id:@user.level_id,functionality_id:functionality_id).count > 0 )
        return true
      else
        return false
      end

    else
      return false
    end

  end

  def getLevel(level)

    if @user != nil

      if ( Level.all.where(id:@user.level_id).first.nombre == level)
        return true
      else
        return false
      end

    else
      return false
    end

  end



  def nombre
    return @user.nombre
  end


end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  def index
    if Usuario.new(session[:user_id]).getFuncionalidad("Administrar Etiquetas")
    @etiquetas=Label.all
    else
      flash[:message]="No tiene acceso a la ruta de recien"
      redirect_to root_path
    end
  end

  def create
    if params[:nombre]!=""#si no esta vacio
      nombreFormato=params[:nombre].capitalize
      if Label.where(nombre:nombreFormato).count==0#Si no existe la etiqueta

         etiqueta=Label.new(nombre: nombreFormato,activo:true)
         if etiqueta.save#si se puede guardar
           redirect_to labels_index_path
         else#Si no se guardo, sale el error
           #este es un mensaje que se guarda en la variable global flash
           flash[:message] = "No se pudo crear la etiqueta"
           redirect_to labels_index_path
         end
       else#Si la etiqueta existe
        if Label.where(nombre:nombreFormato).first.activo==true
         #este es un mensaje que se guarda en la variable global flash
         flash[:message] = "La etiqueta ya existe"
         redirect_to labels_index_path
        else
          etiqueta=Label.where(nombre:nombreFormato).first
          etiqueta.activo = true
          if !etiqueta.save#Si no se guardo, sale el error
           flash[:message] = "No se pudo crear la etiqueta"
          end
          redirect_to labels_index_path
        end
       end
    end
  end

  def show
  end

  def destroy
  end

  def update
    label=Label.find(params[:label_id])
    label.nombre=params[:nombre].capitalize
    label.save
    redirect_to labels_index_path
  end
  def delete
    if session[:user_id]!=0 && Usuario.new(session[:user_id]).getFuncionalidad("Administrar Etiquetas")
      @eti=Label.find(params[:format])
      @eti.activo = false
      @eti.save
      chekeoSinRelaciones
      redirect_to labels_index_path
    end
  end

  def chekeoSinRelaciones
    if QuestionLabel.all.where(label_id:@eti.id).count==0
        @eti.destroy
    end
  end

end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/labels/index.html.erb
<%flash[:auxVerPerfil] = nil%>
<ul class="list-group">
<script type="text/javascript">
function Mostrar(label_id)
{
    formUpdate= "formUpdate" + label_id;
    if(document.getElementById(formUpdate).style.display!="block")
      document.getElementById(formUpdate).style.display="block"
    else
      document.getElementById(formUpdate).style.display="none"
}
</script>


  <%@etiquetas.order(:nombre).each do |etiqueta|%>
  <%if etiqueta.activo == true %>
    <li class="list-group-item">
    <%= etiqueta.nombre %>
    <button type="button" class="btn btn-warning" onclick="Mostrar(<%=etiqueta.id%>)">Modificar</button>
    <%= link_to labels_delete_path(etiqueta.id) do %>
      <button type="button" class="btn btn-danger">Eliminar</button>
    <%end%>
    <form form class="" action="/labels/update" id="formUpdate<%=etiqueta.id%>" method="get" style="display:none;margin-top:10px">
      <div class="form-group">
        <label for="nombre">Nuevo Nombre:</label>
        <input type="text"  name="nombre" id="nombre" required style="text-transform: capitalize">
        <button class="btn  btn-primary" type="submit" >Modificar Etiqueta</button>
        <input type="hidden" class="form-control" name="label_id" id="label_id" value=<%=etiqueta.id%>>
      </div>
    </form>
    </li>
  <%end%>
  <%end%>
<% if session[:user_id] != 0 %>
  <li class="list-group-item">
        <form class="form-inline" action="/labels/create" method="post">
          <div class="form-group">
           <label for="nombre">Nombre:</label>
           <input type="text" class="form-control" name="nombre" id="nombre" style="text-transform: capitalize" pattern="[A-Za-z0-9]+" title="Solo letras y Numeros">
           <button class="btn btn-lg btn-primary btn-block" type="submit" style="margin-top: 20px;">Crear Etiqueta</button>
          </div>

          <% if flash[:message] != nil %>
           <% @color="red" %>
           <%= render '/mensaje/mensaje'  %>
          <% end %>

    </form>
  </li>
  <%end%>

</ul>