config/routes.rb
Rails.application.routes.draw do


  get 'levels/index'
  post 'levels/create'
  get 'levels/delete'
  get 'levels/update'



  resources :questions
  get 'users/index'
  post 'users/create'

  get 'sessions/index'

  root 'questions#index'

  get 'questions/index'
  post 'questions/create'
  get 'questions/update'

  get 'questions/show'
  get 'users/show'
  get 'users/update'

  post 'sessions/create'

  get 'sessions/destroy'

  get 'labels/index'


  post 'labels/create'

  post 'questions_comments/create'
  post 'answers_comments/create'
  post 'answers/create'
  post 'cars/create'
  post 'cats/create'
  post 'dogs/create'
  post 'cows/create'

  get 'labels/delete'
  get 'labels/update'
  
  get 'faculties/index'
  get 'faculties/delete'
  post 'faculties/create'
  get 'faculties/update'
  get 'faculties/show'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  has_many :answer_comments, dependent: :destroy
  has_many :answer_votes, dependent: :destroy
  belongs_to :question
  belongs_to :user
  validates :contenido, presence: true
end

app/models/answer_comment.rb
class AnswerComment < ApplicationRecord
  has_many :answer_comment_votes, dependent: :destroy
  belongs_to :answer
  belongs_to :user
  validates :contenido, presence: true
end

app/models/answer_vote.rb
class AnswerVote < ApplicationRecord
  belongs_to :answer
  belongs_to :user
end

app/models/direction.rb
class Direction < ApplicationRecord
  has_many :faculties
  validates :ciudad, presence: true
  validates :calle, presence: true
end

app/models/faculty.rb
class Faculty < ApplicationRecord
  belongs_to :direction
  has_many :question
  has_many :users
  validates :nombre, presence: true, uniqueness: true
end

app/models/functionality.rb
class Functionality < ApplicationRecord

  has_many :level_functionalities, dependent: :destroy

end

app/models/label.rb
class Label < ApplicationRecord
  has_many :question_labels, dependent: :destroy
  validates :nombre, presence: true, uniqueness: true
end

app/models/level.rb
class Level < ApplicationRecord
  has_many :users
  validates :nombre, presence: true
  validates :puntos, presence: true

  has_many :level_functionalities, dependent: :destroy



end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  has_many :question_comments, dependent: :destroy
  has_many :question_votes, dependent: :destroy
  belongs_to :user
  belongs_to :faculty
  has_many :question_labels, dependent: :destroy
  validates :contenido, presence: true
end

app/models/question_comment.rb
class QuestionComment < ApplicationRecord
  has_many :question_comment_votes, dependent: :destroy
  belongs_to :question
  belongs_to :user
  validates :contenido, presence: true
end

app/models/question_label.rb
class QuestionLabel < ApplicationRecord
  belongs_to :question
  belongs_to :label
end

app/models/question_vote.rb
class QuestionVote < ApplicationRecord
  belongs_to :question
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :level
  belongs_to :faculty, optional:true
  has_many :questions
  has_many :answer
  has_many :question_comments
  has_many :answer_comments
  has_many :question_votes
  has_many :answer_votes
  has_many :question_comment_votes
  has_many :answer_comment_votes
  validates :nombre, presence: true
  validates :apellido, presence: true
  validates :mail, presence: true, uniqueness: true
  validates :pass, presence: true
end

app/models/usuario.rb
class Usuario

  # método inicializar clase
  def initialize(id)

    if id > 0
      @user = User.find(id)
    else
      @user = nil
    end

  end

  def getFuncionalidad(funcionalidad)

    if @user != nil

      functionality_id = Functionality.all.where(nombre:funcionalidad).first.id

      if ( LevelFunctionality.all.where(level_id:@user.level_id,functionality_id:functionality_id).count > 0 )
        return true
      else
        return false
      end

    else
      return false
    end

  end

  def getLevel(level)

    if @user != nil

      if ( Level.all.where(id:@user.level_id).first.nombre == level)
        return true
      else
        return false
      end

    else
      return false
    end

  end



  def nombre
    return @user.nombre
  end


end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Educanding</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>

  <%=
  if session[:user_id] == nil
    session[:user_id] = 0
  end
  %>

  <body>

  <div class="container"></div>
  <div class="row" style="margin-top: 25px;padding-left: 5%;">



    <div class="col-xs-6 col-md-3" style="width: 55%;">
       <%= link_to root_path do %>
       <%= image_tag "educanding_azul.png", title: "Volver al Inicio" ,float:"left" %>
       <%end%>
    </div>
    <div class="col-md-4" style="width: 28%;margin-left: 5%;padding-top: 25px;">
     <ol class="breadcrumb text-center">
       <li class="navIR">
        <%= link_to 'Inicio',root_path  %>
       </li>
     </ol>

        <% if session[:user_id] == 0 %>

          <% if flash[:auxIngReg] == nil  #esta variable auxIngReg se pone no nula cuando se ingresa a iniciar sesion o a registrase %>
            <ol class="breadcrumb text-center">
              <li class="navIR">
                <%= link_to 'Ingresar',sessions_index_path %>
              </li>
              <li class="navIR">
                <%= link_to 'Registrarse',users_index_path %>
              </li>
            </ol>
          <% end %>

        <% else %>
        <ol class="breadcrumb text-center">
          <% if flash[:auxVerPerfil] == nil %>
            <li class="navIR">
                <%= link_to "Perfil: #{User.find(session[:user_id]).nombre} #{User.find(session[:user_id]).apellido}", users_show_path%>
            </li>
          <%end%>
          <li class="navIR">
            <%= link_to 'Cerrar Sesión',sessions_destroy_path %>
          </li>
        </ol>

        <ol class="breadcrumb text-center">


          <% if Usuario.new(session[:user_id]).getFuncionalidad("Administrar Etiquetas")%>
            <li class="navIR">
              <%= link_to 'Etiquetas',labels_index_path %>
            </li>
          <%end%>

          <% if Usuario.new(session[:user_id]).getFuncionalidad("Administrar Facultades")%>
            <li class="navIR">
              <%= link_to 'Facultades',faculties_index_path %>
            </li>
          <%end%>


          <% if User.find(session[:user_id]).admin == true || Usuario.new(session[:user_id]).getLevel("Administradortotal")%>

                <li class="navIR">
                <%= link_to 'Niveles',levels_index_path %>
                </li>

          <% end %>



        </ol>

        <% end %>
    </div>
  </div>



    <%= yield %>


  </body>
</html>

app/views/mensaje/_mensaje.html.erb
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<div class="w3-panel w3-<%=@color%> w3-display-container" style="margin-top: 50px;">
  <span onclick="this.parentElement.style.display='none'"class="w3-button w3-<%=@color%> w3-large w3-display-topright">&times;</span>
  <h4 class="mb-1 text-center">Atención!</h4>
  <br>
  <p class="mb-1 text-center"><%= flash[:message] %></p>
  <%$recargar=nil%>
  <%flash[:message]=nil%>
</div>
<%@color=nil%>